service:
  name: serverless-todo-app

plugins:
  - serverless-webpack
  - serverless-aws-documentation
  - serverless-attach-permission-boundary
  - serverless-iam-roles-per-function


provider:
  name: aws
  runtime: nodejs10.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  permissionsBoundaryArn: "arn:aws:iam::913348900614:policy/acs/acs-boundary-policy"
  rolePermissionsBoundary: "arn:aws:iam::913348900614:policy/acs/acs-boundary-policy"
  tracing:
    lambda: true
    apiGateway: true
  environment:
    TODOS_TABLE: Datagram264TodosTable-${self:provider.stage}
    INDEX_NAME: I_DueDate
    TODOS_S3_BUCKET: datagram264todosbucket-${self:provider.stage}
custom:
  documentation:
    api:
      info:
        version: "1"
        title: "serverless-todo-app"
        description: "Api for udacity lesson 4"
functions:

  HS256Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  # TODO: Configure this function
  GetTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      - http:
          method: get
          path: todos
          authorizer: HS256Auth
          cors: true
          documentation:
            summary: Get all Todo Items for User
            description: Get all Todo Items for User
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.INDEX_NAME}

  # TODO: Configure this function
  CreateTodo:
    handler: src/lambda/http/createTodo.handler
    events:
      - http:
          method: post
          path: todos
          authorizer: HS256Auth
          cors: true
          documentation:
            summary: Create a Todo Item
            description: Create a Todo Item
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}

  # TODO: Configure this function
  UpdateTodo:
    handler: src/lambda/http/updateTodo.handler
    events:
      - http:
          method: patch
          path: todos/{todoId}
          authorizer: HS256Auth
          cors: true
          documentation:
            summary: Update a Todo Item
            description: Update a Todo Item
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.INDEX_NAME}
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}
  # TODO: Configure this function
  DeleteTodo:
    handler: src/lambda/http/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}
          authorizer: HS256Auth
          cors: true
          documentation:
            summary: Delete a Todo Item
            description: Delete a Todo Item
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.INDEX_NAME}
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}
# TODO: Configure this function
  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment
          authorizer: HS256Auth
          cors: true
          documentation:
            summary: Generate Upload Url
            description: Generate Upload Url
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: arn:aws:s3:::${self:provider.environment.TODOS_S3_BUCKET}/*
resources:
  Resources:
    TodosTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: dueDate
            AttributeType: S
          - AttributeName: todoId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: todoId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.TODOS_TABLE}
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEX_NAME}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: dueDate
                KeyType: RANGE
            Projection:
              ProjectionType: ALL # What attributes will be copied to an index
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.TODOS_S3_BUCKET}
        Tags:
          - Key: 'Allowed_Public_Access'
            Value: 'True'
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
#    BucketPolicy:
#      Type: AWS::S3::BucketPolicy
#      Properties:
#        PolicyDocument:
#          Id: udagramdatadev264Policy
#          Version: '2012-10-17'
#          Statement:
#            - Sid: PublicReadForGetBucketObjects
#              Effect: Allow
#              Principal: '*'
#              Action: 's3:GetObject'
#              Resource: 'arn:aws:s3:::${self:provider.environment.TODOS_S3_BUCKET}/*'
#        Bucket: !Ref AttachmentsBucket
